// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN2McacTs5kKbfS2Lc5umzutLqZkHuQso',
    appId: '1:508290113524:web:90b1c90bb8b7ccc4dd63a1',
    messagingSenderId: '508290113524',
    projectId: 'ta-capstone-22597',
    authDomain: 'ta-capstone-22597.firebaseapp.com',
    databaseURL: 'https://ta-capstone-22597-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ta-capstone-22597.appspot.com',
    measurementId: 'G-S9RRP8YJ86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnMmIRmKLkbF3TQo8ITKvRwXJV6fu_vLU',
    appId: '1:508290113524:android:1a237d7531b5a805dd63a1',
    messagingSenderId: '508290113524',
    projectId: 'ta-capstone-22597',
    databaseURL: 'https://ta-capstone-22597-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ta-capstone-22597.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1OKXOQPB0_71T2JcZNW3Bkr866LY8CqQ',
    appId: '1:508290113524:ios:6beeeb6075c7a767dd63a1',
    messagingSenderId: '508290113524',
    projectId: 'ta-capstone-22597',
    databaseURL: 'https://ta-capstone-22597-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ta-capstone-22597.appspot.com',
    iosBundleId: 'com.example.koiaqua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1OKXOQPB0_71T2JcZNW3Bkr866LY8CqQ',
    appId: '1:508290113524:ios:6beeeb6075c7a767dd63a1',
    messagingSenderId: '508290113524',
    projectId: 'ta-capstone-22597',
    databaseURL: 'https://ta-capstone-22597-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ta-capstone-22597.appspot.com',
    iosBundleId: 'com.example.koiaqua',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN2McacTs5kKbfS2Lc5umzutLqZkHuQso',
    appId: '1:508290113524:web:fda194d6d440c506dd63a1',
    messagingSenderId: '508290113524',
    projectId: 'ta-capstone-22597',
    authDomain: 'ta-capstone-22597.firebaseapp.com',
    databaseURL: 'https://ta-capstone-22597-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ta-capstone-22597.appspot.com',
    measurementId: 'G-N0SXRE2R4K',
  );

}