// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN2McacTs5kKbfS2Lc5umzutLqZkHuQso',
    appId: '1:508290113524:web:5f11daba36b372e2dd63a1',
    messagingSenderId: '508290113524',
    projectId: 'ta-capstone-22597',
    authDomain: 'ta-capstone-22597.firebaseapp.com',
    databaseURL: 'https://ta-capstone-22597-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ta-capstone-22597.appspot.com',
    measurementId: 'G-CX92GH2C7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnMmIRmKLkbF3TQo8ITKvRwXJV6fu_vLU',
    appId: '1:508290113524:android:a40b5bd808c943b5dd63a1',
    messagingSenderId: '508290113524',
    projectId: 'ta-capstone-22597',
    databaseURL: 'https://ta-capstone-22597-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ta-capstone-22597.appspot.com',
  );
}
